version: '3.7'

services:
  postgres:
    env_file: .env
    image: mdillon/postgis
    restart: always
    environment:
      POSTGRES_DATABASE: '${POSTGRES_DATABASE}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      PGDATA: db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  db_data:
